wait("start-setup.png", 60)
click("start-setup.png")

wait("typing.png")
click(Pattern("search-bar.png").similar(0.78))
type("english us")
wait("english-us.png")
click("english-us.png")

wait("location_services.png")
click("location_services.png")
click("next.png")

wait("time_zone.png")
click(Pattern("search-bar.png").similar(0.78))
type("helsinki")
wait("helsinki_finland.png")
click("helsinki_finland.png")
click("next.png")
click("skip.png")

click(Pattern("full_name.png").targetOffset(70,0))
type("Dustin Henderson")
wait("dustinhenderson.png")
click("next.png")
click(Pattern("password.png").targetOffset(82,-5))
type("herp-derp")
click(Pattern("confirm.png").targetOffset(75,2))
type("herp-derp")
click("next.png")
wait("1675117858609.png")
click("1675117869858.png")