name: e2e-test

on:
  push:
    branches:
      - main
      - e2e-test
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: test

jobs:
  e2e-test:
    runs-on: self-hosted
    steps:
      - name: Get job ID URL
        uses: Tiryoh/gha-jobid-action@v0
        id: job_id
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}
      
      - name: Output Current Job Log URL
        run: echo ${{ steps.jobs.outputs.html_url }}
    
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Symlink the iso to use in.
        run: ln -s ~/Developer/iso/lunar-desktop-amd64.iso .
      
      - name: Copy spice config in place
        run: cp spicy-settings ~/.config/spicy/settings 
      
      #- name: Run the Lunar installer automation
      #  run: ./bin/install-lunar.sh
      #  env:
      #    SIKULIX_JAR: /home/mz2/java/lib/sikulixide.jar

      - name: Check for presence of test/screenshot.png
        id: screenshot_check
        run: |
          if test -f screenshot.png; then
            echo "screenshot_present=true" >> $GITHUB_OUTPUT
          else
            echo "screenshot_present=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Archive failing screenshot
        uses: actions/upload-artifact@v3
        if: steps.screenshot_check.outputs.screenshot_present == 'true'
        with:
          name: archive-failing-screenshot
          path: test/screenshot.png
          
      - uses: JasonEtco/create-an-issue@v2
        if: steps.screenshot_check.outputs.screenshot_present == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JOB_ID: ${{ steps.job_id.outputs.job_id }}
          HTML_URL: ${{ steps.job_id.outputs.html_url }}
        with:
          filename: .github/e2e-fail-issue-template.md  