name: e2e-test

on:
  push:
    branches:
      - main
      - e2e-test
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: test

jobs:
  e2e-test:
    runs-on: self-hosted
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Symlink the iso to use in.
        run: ln -s ~/images/lunar-desktop-amd64.iso .

      - name: Copy spice config in place
        run: cp spicy-settings ~/.config/spicy/settings

      - name: Run the Lunar installer automation (blank starting point -> Ubuntu installed on its own)
        run: ./bin/install-lunar.sh blank
        env:
          SIKULIX_JAR: ~/java/lib/sikulixide.jar

      - name: Check for presence of test/screenshot.png
        id: screenshot_check
        run: |
          if test -f screenshot.png; then
            echo "screenshot_present=true" >> $GITHUB_OUTPUT
          else
            echo "screenshot_present=false" >> $GITHUB_OUTPUT
          fi

      - name: Archive failing screenshot
        uses: actions/upload-artifact@v3
        if: steps.screenshot_check.outputs.screenshot_present == 'true'
        with:
          name: failing-screenshot
          path: test/screenshot.png

      - name: Construct the run URL
        run: echo "run_url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" >> $GITHUB_OUTPUT
        id: run_url

      - uses: JasonEtco/create-an-issue@v2
        if: steps.screenshot_check.outputs.screenshot_present == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_URL: ${{ steps.run_url.outputs.run_url }}
        with:
          filename: .github/ISSUE_TEMPLATE/e2e-test-fail.md
