name: e2e-test

on:
  push:
    branches:
      - main
      - e2e-test
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: test

jobs:
  e2e-test:
    runs-on: self-hosted
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Symlink the iso to use in.
        run: ln -s ~/Developer/iso/lunar-desktop-amd64.iso .
      
      - name: Copy spice config in place
        run: cp spicy-settings ~/.config/spicy/settings 
      
      - name: Run the Lunar installer automation
        run: ./bin/install-lunar.sh
        env:
          SIKULIX_JAR: /home/mz2/java/lib/sikulixide.jar
